### ISSUE TITLE
Add additional data into `PoolCreated` event response

### ISSUE THREAD

**Issue by mckrava** [galacticcouncil/Basilisk-node#128]
we have such event:
```
/// Pool was created. [who, asset a, asset b, initial shares amount]
PoolCreated(T::AccountId, AssetId, AssetId, Balance),
```

Is it possible to provide additional data in event response:
- [ ] newly created pool address;
- [ ] `id` (or more details) of shared token of newly created pool;

**Comment by enthusiastmartin** [comment]
Actually, with the new asset registry - there will be new event - coming from the registry itself. The registry will deposit event called `Registered` when new asset is being added to the registry.

So this would help too.

It does not change this PR tough as the info in amm event is useful regardless.

**Comment by mckrava** [comment]
`Registered` more or less will solve my issue with shared token, however, receiving shared token id directly from `PoolCreated ` even will reduce number of processing movements with shared token data. 

And still getting newly created pool address - it's super critical thing :(

**Comment by jak-pan** [comment]
@Roznovjak can you pls look at this?

**Comment by enthusiastmartin** [comment]
Done here, let's just port the change - it must the same

https://github.com/galacticcouncil/HydraDX-node/pull/300

**Comment by Roznovjak** [comment]
`PoolCreated` and `PoolUpdated` events have been updated and now contain `PoolId` and `Pool` struct.
