### ISSUE TITLE
refactor: remove AssetPairAccountId from pallet config

### ISSUE THREAD

**Issue by enthusiastmartin** [galacticcouncil/Basilisk-node#129]
### Description
Pallets xyk and lbp ( and hdx in future ) have so called AssetPairAccountId as type in their configs.  Eg: 

`type AssetPairAccountId: AssetPairAccountIdFor<AssetId, Self::AccountId>;`

The trait is is always provided by the pallet! and it is always  implemented by the pallet itself too. 

It does not actually make much sense to have any other implementation. 

This is actually related closely to the pallet itself to generate token names how it needs.

The only part needed is the infix string used when generate a shared asset name .eg "100hdx200". This is used to differentiate between shared asset  created by xyk or lbp pallet which creates shared asset between same assets.

One solution could be that this is part of the AssetPair struct - just need to work you how to do with the infix.

**Comment by jak-pan** [comment]
What is status of this issue?

**Comment by Roznovjak** [comment]
> What is status of this issue?

I have encountered som issues with traits and I wasn't able to solve it. I am going to look at it again.
