### ISSUE TITLE
refactor: generic AMM trait 

### ISSUE THREAD

**Issue by enthusiastmartin** [galacticcouncil/Basilisk-node#145]
Yeah, i was actually thinking that this AMM trait should be more generic to cover various pool implementations.

I have some ideas - but do we want to refactor now ?

_Originally posted by @enthusiastmartin in https://github.com/galacticcouncil/Basilisk-node/pull/144#discussion_r698443851_

**Comment by lumir-mrkva** [comment]
@enthusiastmartin still and issue or can be closed?

**Comment by enthusiastmartin** [comment]
> 
> 
> @enthusiastmartin still and issue or can be closed?

No, not really. It was an idea but tbh, it is not really worth the effort.
