### ISSUE TITLE
refund tx fee if paid in non-native currency

### ISSUE THREAD

**Issue by enthusiastmartin** [galacticcouncil/Basilisk-node#166]
Currently, it is not possible to refund any tx fee if fee is paid in non-native currency. 

This is due to the fact that payment module does not track the fee amount when fee is withdrawn ( only in non-native currency )

line 480: `PaymentSwapResult::Transferred => Ok(None),`

The other thing is what currency to refund ? native or selected non-native asset? 

If we wanted to refund in non-native - this would require to perform swap back to non-native currency - another amm swap fee would be taken, additional weight etc.

**Comment by lumir-mrkva** [comment]
this should be already possible because we are withdrawing and depositing non-native fees similarly to the native one. maybe it is already fixed then? @Roznovjak

**Comment by Roznovjak** [comment]
> this should be already possible because we are withdrawing and depositing non-native fees similarly to the native one. maybe it is already fixed then? @Roznovjak

Yes, [this PR](https://github.com/galacticcouncil/warehouse/pull/42) fixes this issue.

**Comment by enthusiastmartin** [comment]
fixed.
