### ISSUE TITLE
avoid auto trading my ob order on amm dex

### ISSUE THREAD

**Issue by dzmitry-lahoda** [galacticcouncil/Basilisk-node#176]
# case

>> If there are any intentions left in the second group( have not been matched ) - all are traded through AMM.

1. I put order for 100 A tokens for 10 USD each.
2. There is no match on OB for these.
3. AMM can buy 100 A tokens for 8 USD each.

Actual: My 100 A tokens are sold for 8 USD each
Expected: My order canceled or retained to next block

# solution

please document better what happens, is limit prevents doing unwanted trade via AMM? is order removed from storage and should be retried.

**Comment by enthusiastmartin** [comment]
Hi,

That's how the algorithm currently works.

It is documented here - step 5:

[Exchange Readme](https://github.com/galacticcouncil/Basilisk-node/tree/master/pallets/exchange#order-matching-algorithm)

But good news is that the whole algorithm is being redesigned and re-implemented at the moment. And your suggested solution will be part of the new implementation in one way or another.
