### ISSUE TITLE
Add workflow to build dev docker images

### ISSUE THREAD

**Issue by dexterslabor** [galacticcouncil/Basilisk-node#193]
### Detailed Description

Add a workflow that builds docker images of a ready to test basilisk node in a development sandbox setup.

### Context

A docker image will save a lot of time in the automation of [SDK](https://github.com/galacticcouncil/HydraDX-js) testing. An open issue can be found at https://github.com/galacticcouncil/HydraDX-js/issues/21. Without a docker image, the CI would need to build the basilisk node and setup the `polkadot-launch` command that can easily take more than 30 minutes. Automated testing helps to maintain all checks that results in robust software, whether basilisk node is updated or the SDK.

### Possible Implementation

Add a docker build workflow on each new release or merge to the `master` branch and publish to a registry such as GitHub or Docker Hub.
The resulting image should have a ready to use development chain that follows the `Rococo local testnet` setup.

**Comment by lumir-mrkva** [comment]
docker image will contain the whole rococo dev environment and it will start polkadot launch with container

**Comment by lumir-mrkva** [comment]
fixed by https://github.com/galacticcouncil/Basilisk-api/pull/23

**Comment by lumir-mrkva** [comment]
https://github.com/galacticcouncil/Basilisk-api/pull/27
