### ISSUE TITLE
SS58 prefix

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/Basilisk-node#21]

**Comment by lumir-mrkva** [comment]
requires https://github.com/paritytech/substrate/pull/8882

**Comment by jak-pan** [comment]
It's in Substrate. Do we close or wait for update to that version?

**Comment by lumir-mrkva** [comment]
@jak-pan update basilisk chain spec as well

**Comment by lumir-mrkva** [comment]
blocked by https://github.com/paritytech/substrate/pull/8955
