### ISSUE TITLE
chore: upgrade to polkadot 0.9.12

### ISSUE THREAD

**Issue by lumir-mrkva** [galacticcouncil/Basilisk-node#214]
- [x] orml ready
- [ ] upgrade deps

**Comment by lumir-mrkva** [comment]
@green-jay i dont think we can skip any version since most of them are not compatible with earlier ones, we have to do it to just continue block production of snek

**Comment by green-jay** [comment]
this one supposedly is not breaking so I was hoping we could...but since 0.9.11 is considered a malicious node i suppose we have no other choice but to upgrade
