### ISSUE TITLE
Improve XYK events order

### ISSUE THREAD

**Issue by dexterslabor** [galacticcouncil/Basilisk-node#245]
# Detailed Description

The creation of a XYK pools emits the following events (in this order):

1. balances.Endowed
1. balances.Transfer
1. currencies.Transferred
1. tokens.Endowed
1. tokens.Transfer
1. currencies.Deposited
1. xyk.PoolCreated

The improvement is to emit xyk.PoolCreated before any balance and token transfers events.

# Context

XYK.PoolCreated event contains the pool_id. When processing balance and token transfers, it is crucial to limit the processing only to transfers of interest. That's why it is essential to know the pool_id beforehand.

# Possible Implementation

The indexer strictly follows the order as the events are emitted. It is not intended to change this order when processing. Therefore it is not a desired approach to build an exception for this case.

A possible implementation is to change the order of events. The following would pose a viable solution:

1. xyk.PoolCreated
1. balances.Endowed
1. balances.Transfer
1. currencies.Transferred
1. tokens.Endowed
1. tokens.Transfer
1. currencies.Deposited

**Comment by enthusiastmartin** [comment]
Fixed in #246
