### ISSUE TITLE
Bug: RPC-01 disconnect from basilisk network

### ISSUE THREAD

**Issue by martinfridrich** [galacticcouncil/Basilisk-node#260]
rpc-01(sometimes) drop all peers and don't reconnect until basilisk db is removed

**Comment by jak-pan** [comment]
Can we check this with parity?

**Comment by martinfridrich** [comment]
We did : `we have imported too many blocks on the same height`. It looks like It's running ok since we added a daily restart script but it’s only about a week. I'll monitor if it happens again.
