### ISSUE TITLE
Disable remark for non-governance use

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/Basilisk-node#304]
We should disable calling remarks without either going through governance or other pallets to prevent spam.

**Comment by lumir-mrkva** [comment]
mby just artificially increase cost of the remark

**Comment by Roznovjak** [comment]
It looks like it is not possible to use `CallFilter` for this. The `Call` parameter used is the filter doesn't carry the information about `origin`. https://docs.substrate.io/rustdocs/latest/frame_system/pallet/enum.Call.html
