### ISSUE TITLE
XCM: add deposit error handler for multi-currency adapter

### ISSUE THREAD

**Issue by enthusiastmartin** [galacticcouncil/Basilisk-node#334]
more info -> https://github.com/open-web3-stack/open-runtime-module-library/pull/675

_Originally posted by @lumir-mrkva in https://github.com/galacticcouncil/Basilisk-node/pull/328#discussion_r791593408_

**Comment by lumir-mrkva** [comment]
currently the default implementation is used

**Comment by enthusiastmartin** [comment]
I think we should use `DepositToAlternative `implementation.

this will deposit to selected alternative account ( eg. treasury ) instead of failure. 

@lumir-mrkva what you think ?

**Comment by lumir-mrkva** [comment]
i agree that is better to deposit token somewhere than just ignoring it, but i would create some special account for this use case
