### ISSUE TITLE
Nodes for Karura testnet

### ISSUE THREAD

**Issue by mrq1911** [galacticcouncil/Basilisk-node#408]
2 collators + 1 rpc node for karura testnet

- collators have to have 30333 open and assigned to predefined bootnode addresses (TBD)
- RPC node will have reverse proxy WSS (443) -> localhost:9988

**Comment by fakirAyoub** [comment]
Depends on https://github.com/galacticcouncil/infrastructure/issues/35

**Comment by fakirAyoub** [comment]
Waiting for Karura to open relaychain and send us the new chainspec. ETA: 28/03
