### ISSUE TITLE
Bug: NFT Pallet should emit metadata set event

### ISSUE THREAD

**Issue by vikiival** [galacticcouncil/Basilisk-node#416]
### Description
As I spoke with the subquery guys they recommend to index Events rather than extrinsics. 
However, I cannot catch metadata for Class/Instance because there is no such event.
The original unique pallet emits `MetadataSet` event.

### Expected Behavior
I would love to extend the `ClassCreated` and `InstanceMinted` events with the metadata field :).

### Actual Behavior
~

### Possible Fix
A possible fix is explained in the Expected Behavior section.

The second possible fix is to emit `MetadataSet` in the same manner as the unique pallet - however.

**Comment by vikiival** [comment]
May @green-jay can take a look

**Comment by green-jay** [comment]
solved

**Comment by vikiival** [comment]
And what's the final result? Can't find a related PR or commit

**Comment by green-jay** [comment]
> 

changes done in `feat/marketplace` branch and deployed to the testnet

**Comment by vikiival** [comment]
Found the commit 110ac81b517647e72ac65ec4041266660eb4cdb0
