### ISSUE TITLE
Bug: Basilisk-Karura.json error on Ubuntu 21.10

### ISSUE THREAD

**Issue by dudo50** [galacticcouncil/Basilisk-node#421]
Getting error starting json

### Description
Starting Basilisk-Karura.json file with polkadot-launch gives error, despite the fact, that Acala is in correct directory and built. This issue is on Ubuntu 21.10
### Expected Behavior
Launching Polkadot relay chain and 2 parachains

### Actual Behavior
Basilisk chain starts, but Karura chain fails to start due:
[Error: Input("Error opening spec file `karura-dev`: No such file or directory (os error 2)")

Killing all processes...
undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at getParachainIdFromSpec (/usr/local/share/.config/yarn/global/node_modules/polkadot-launch/dist/spawn.js:72:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async resolveParachainId (/usr/local/share/.config/yarn/global/node_modules/polkadot-launch/dist/runner.js:183:28)
    at async run (/usr/local/share/.config/yarn/global/node_modules/polkadot-launch/dist/runner.js:44:20)](url)

### Steps to Reproduce
1. Having Polkadot, Acala and Basilisk installed in same Directory for example: Project / Acala, Project / Polkadot, Project/ Basilisk-node
2. Navigating to Basilisk-node/rococo-local
3. Starting command polkadot-launch basilisk-karura.json

### Context
I need to create channel between two parachains to transfer fungible tokens between them

### Your Environment

* Toolchain versions: rustup - nightly / newest version , node 16.14, Polkadot, Basilisk and Acala all newest versions pulled yesterday

* Operating System and version: Ubuntu 21.10
* System specs: 8gb ram, 256gb ssd ,i5 8250u

Screenshot of issue
![Screenshot from 2022-04-01 22-11-05](https://user-images.githubusercontent.com/55763425/161335683-b61d23a8-85c0-44d9-817b-0dbddbc76ee9.png)

**Comment by green-jay** [comment]
Hi, what command did you use to build Acala node with?

**Comment by dudo50** [comment]
Hi, sorry for late reply, but it was make init and then make build-full

**Comment by green-jay** [comment]
> Hi, sorry for late reply, but it was **make init** and then **make build-full**

That does not make much sense, since `make init` runs `make build-full` already.
Moreover `make build-full` runs: `cargo build --features with-mandala-runtime`.
Our config expects karura-runtime with its binary in the target/release folder.
From what I can see `make build-karura-internal-release` might provide you with what you need, or alternatively change the binary path in the config

**Comment by dudo50** [comment]
This command results into following error: 

```
error: failed to load manifest for workspace member `/mnt/data/chains/Acala/node`

Caused by:
  failed to load manifest for dependency `acala-cli`

Caused by:
  failed to load manifest for dependency `acala-service`

Caused by:
  failed to load manifest for dependency `acala-primitives`

Caused by:
  failed to load manifest for dependency `nutsfinance-stable-asset`

Caused by:
  failed to read `/mnt/data/chains/Acala/ecosystem-modules/stable-asset/lib/stable-asset/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
make: *** [Makefile:55: build-karura-internal-release] Error 101

```

**Comment by dudo50** [comment]
Okay, it needed `make init,` now it is working. Thank you

**Comment by dudo50** [comment]
Now however I do get different kind of error launching .json  `API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed`
which means relay chain is not available, could this be issue with polkadot folder or something like that? I made sure to get 0.9.18 and to compile it using cargo build --release
