### ISSUE TITLE
OfferPlaced does not emit expire block

### ISSUE THREAD

**Issue by vikiival** [galacticcouncil/Basilisk-node#425]
### Description
Currently it's not possible for the indexers to obtain a blocknumber where the offer expires :)

### Expected Behavior
```rs
Self::deposit_event(Event::OfferPlaced(sender, class_id, instance_id, amount, expires));
```

### Actual Behavior
```rs
Self::deposit_event(Event::OfferPlaced(sender, class_id, instance_id, amount));
```

cc @green-jay (priority one pls)

**Comment by green-jay** [comment]
Fixed: https://github.com/galacticcouncil/Basilisk-node/commit/63720a37d89bd65fc55f51c57e39879b72b67299
