### ISSUE TITLE
Add pallet identity

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/Basilisk-node#451]

**Comment by vikiival** [comment]
Cool idea 🚀

**Comment by Roznovjak** [comment]
Identity pallet has been already configured in the runtime.

**Comment by vikiival** [comment]
> Identity pallet has been already configured in the runtime.

Where commit 👁️

**Comment by Roznovjak** [comment]
> > Identity pallet has been already configured in the runtime.
> 
> Where commit 👁️

#481
