### ISSUE TITLE
Change fee payment token on account create, transfer or xcm transfer

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/Basilisk-node#454]
**Description**
If we are creating new account on the chain the fee payment asset could be set to the asset that was transferred to that account. 

**Why**
The idea is that you don't need to do extra transaction when you transfer tokens to new account (disregarding bsx). This would greatly improve UX inside the chain because user doesn't need to do 2 transactions himself (If the account is new, including no system account (or has no fee payment balance) user would need to do second TX. I'm proposing to create a hook that will do this automagically after any transfer / lock. This can be tricky however.

**Possible problems**
- [ ] If the account is programatic (i.e. pool) we might not want to do this.
- [ ] If the account has been created before we also might not want to do this as it can cause confusion that different actions do or not do this for you.
- [x] If somebody spams you with some useless asset it will be changed for you and it will be very confusing.
- [ ] ???

**Comment by jak-pan** [comment]
I would like to get some reasoning here why yes why not. My biggest concern is with spam. It is not as big of a problem since we're always checking your fee payment asset pre-tx signing and prompt you to change it if you don't have any / enough balance.

**Comment by apopiak** [comment]
Based on discussion elsewhere we will want to implement this by adding a callback to ORML tokens (likely [here](https://github.com/open-web3-stack/open-runtime-module-library/blob/39057dae9c277e34a8e1c61abf2148158199e687/tokens/src/lib.rs#L752)) for newly created accounts that includes the asset id and would thus allow us to set it as the fee asset id.

**Comment by apopiak** [comment]
Callback implementation here: https://github.com/open-web3-stack/open-runtime-module-library/pull/754

**Comment by apopiak** [comment]
Callback types here: https://github.com/galacticcouncil/warehouse/pull/54
