### ISSUE TITLE
Use GeneralIndex instead of GeneralKey for currency ids

### ISSUE THREAD

**Issue by green-jay** [galacticcouncil/Basilisk-node#465]
Storage effectivity reasons. GeneralKey is `Vec<u8>` and GeneralIndex is compact `u128`.

Goal is to change XCM configuration so that it uses GeneralIndex type for currency multilocation Junctions.

Companion: https://github.com/galacticcouncil/HydraDX-node/issues/411

**Comment by enthusiastmartin** [comment]
Same should be done in Hydra parachain.

**Comment by lumir-mrkva** [comment]
please notify moonriver about this change
