### ISSUE TITLE
Determine price of filled block

### ISSUE THREAD

**Issue by lumir-mrkva** [galacticcouncil/Basilisk-node#52]
- [x] What is the cost of using all weight in a block in BSX?
- [x] tune cost
- [ ] set cost in USD value for stablecoin fallback price

**Comment by Roznovjak** [comment]
TX fee is computed as `fee = base_fee + length_fee + weight_fee`. If we substitute the `length_fee` and `weight_fee` with the `maximum_block_lenght` and `maximum_block_weight`, we get the result `1_500_268_037_160 ~= 0.015 $ per block`.

Values used in the computation:
`extrinsic_base_weight = 125 * WEIGHT_PER_MICROS = 125_000_000` `pallet_transaction_multi_payment::WeightInfo::swap_currency() = 139_105_000`
`base_fee = extrinsic_base_weight + swap_currency = 264_105_000`
`maximum_block_lenght` for `Normal` dispatch class = `5 MB * 0.75 = 3_932_160`
`maximum_block_weight` for `Normal` dispatch class = `2 * WEIGHT_PER_SECOND * 0.75 = 1_500_000_000_000`
`1 BSX = 1_000_000_000_000`
`100 BSX ~= 1 $`
