### ISSUE TITLE
Bug: BSX Rococo is missing event data

### ISSUE THREAD

**Issue by vikiival** [galacticcouncil/Basilisk-node#539]
Following features are missing / are not implemented on the Basilisk Rococo instance:

- #416
- #457 

pls @lumir-mrkva @green-jay 🔝 📦 ⛓️

**Comment by lumir-mrkva** [comment]
can you please link to the blocks that show this issue?

**Comment by vikiival** [comment]
https://calamar.play.hydration.cloud/extrinsic/0000536030-000002-cccc9

**Comment by enthusiastmartin** [comment]
pallet-nft is now used from wareouse repository. Unfortunately , it seems that this change is not in that version of pallet.

the change has been done in nft pallet but when it was still part of basilisk-repo but was not ported back to warehouse.

**Comment by vikiival** [comment]
Wen deploy?

**Comment by enthusiastmartin** [comment]
> Wen deploy? 🚀 ![6orfmi](https://user-images.githubusercontent.com/22471030/182562836-8846f5ad-cf37-45d4-8cb5-7cfad0f8d75d.jpg)

updating to latest warehouse revision. but unfortunately, there is some unexpected issue which I am trying to resolve (not related to nft pallet ).
