### ISSUE TITLE
Bug: Unable to withdraw offer on burned NFT

### ISSUE THREAD

**Issue by petersopko** [galacticcouncil/Basilisk-node#543]
![image](https://user-images.githubusercontent.com/73316633/183062274-5a708f41-bf17-4dce-abb5-75f7743f7252.png)

![image](https://user-images.githubusercontent.com/73316633/183061996-a9dc3a96-5f93-4121-83c7-0e4ec4f19e9d.png)

### Description
I'm trying to withdraw offer on burned NFT, but there's a `marketplace.ClassOrInstanceUnknown` error
class: 3889603748
instance: 1
https://beta.kodadot.xyz/bsx/gallery/3889603748-1
![image](https://user-images.githubusercontent.com/73316633/183063575-def24b51-d5b4-48fa-8b98-da12e38cc721.png)

### Expected Behavior
I should be able to withdraw this offer.

### Actual Behavior
I'm unable to withdraw offer.

### Steps to Reproduce

1.
2.
3.

### Your Environment

* Toolchain versions: 
* Version used:
* System type: 
* Operating System and version:
* System specs:

**Comment by Roznovjak** [comment]
Thanks for reporting this issue. The issue was fixed in the runtime version 60.
