### ISSUE TITLE
Change deprecated polkadot-launch library for parachain-launch

### ISSUE THREAD

**Issue by dudo50** [galacticcouncil/Basilisk-node#546]
My suggestion:

Replace startup guide which uses deprecated library polkadot-launch for one that is maintained. For example parachain-launch.

Thanks for consideration

**Comment by Roznovjak** [comment]
There are 2 projects to consider: parachain-launch and zombienet.

**Comment by dudo50** [comment]
Any updates on this? Would be very useful if we get some parachain-launch or zombienet configs for Basilisk

**Comment by jak-pan** [comment]
Deprecated for chopsticks? (can reopen if still wanted)
