### ISSUE TITLE
Bug: Cannot add liquidity to XYK if limit is set higher than balance

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/Basilisk-node#553]
https://github.com/galacticcouncil/Basilisk-node/blob/7a1bddd4670c7dcc4b14489b8b5799685f91246d/pallets/xyk/src/lib.rs#L410-L413

This line specifically forbids you to add to the pool even though the tx would have passed if you set high max limit which should not be the case. I would personally remove this condition.

**Comment by Roznovjak** [comment]
> https://github.com/galacticcouncil/Basilisk-node/blob/7a1bddd4670c7dcc4b14489b8b5799685f91246d/pallets/xyk/src/lib.rs#L410-L413
> 
> This line specifically forbids you to add to the pool even though the tx would have passed if you set high max limit which should not be the case. I would personally remove this condition.

What about replacing it with `ensure!(T::Currency::free_balance(asset_b, &who) >= amount_b, ...` where `amount_b` is the actual amount that will be deducted from the account? To keep the errors consistent...

**Comment by enthusiastmartin** [comment]
> https://github.com/galacticcouncil/Basilisk-node/blob/7a1bddd4670c7dcc4b14489b8b5799685f91246d/pallets/xyk/src/lib.rs#L410-L413
> 
> This line specifically forbids you to add to the pool even though the tx would have passed if you set high max limit which should not be the case. I would personally remove this condition.

yes.agreed. 

this check can be removed.  

richard's suggestions can be added instead.
