### ISSUE TITLE
change: xyk - check max out/in ratio in sell/buy

### ISSUE THREAD

**Issue by enthusiastmartin** [galacticcouncil/Basilisk-node#566]
In XYK, currently only the specified amount is checked against max allowed in/out reserve ratio.

eg. 
in sell - only amount_in is checked to be <= reserve / MaxInRatio
in buy - only amount_out is checked to be <= reserve/ MaxOutRatio.

It might be worth to check the amount out in sell, and amount in in buy as well. Similar to what we do in LBP or Omnipool. 

@jak-pan wdyt ?

**Comment by jak-pan** [comment]
We can, but this is not as critical because there is no reason to expect math errors like in omnipool. So it's not critical.
