### ISSUE TITLE
Use transaction-multi-payment from hydradx-node

### ISSUE THREAD

**Issue by enthusiastmartin** [galacticcouncil/Basilisk-node#6]
### Description
Use pallet-transaction-multi-payment from hydradx-node repo to avoid having the same pallet in multiple places.

### Actual status
Currently, the tx multi payment is not possible to use from hydradx-node due to incompatible subtrate versions used. 

And therefore, this pallet is still present locally in this repo.

### Expected status
Remove local pallet and use one from hydradx-repo when ready.

---

required by #25

**Comment by lumir-mrkva** [comment]
this task is required by #25

**Comment by lumir-mrkva** [comment]
we'll need some hardcoded exchange rate for stablecoin as fallback before LBP

**Comment by lumir-mrkva** [comment]
also would be nice to have hardcoded KSM, but not necessary. only stablecoin should be required to participate in LBP - that is theoretically already better UX than balancer LBP :)

**Comment by enthusiastmartin** [comment]
This is already done. Basilisk uses payment pallet from the hydradx-node.
