### ISSUE TITLE
set maximum multiplier

### ISSUE THREAD

**Issue by mrq1911** [galacticcouncil/Basilisk-node#613]
shouldn't be this set to less than impossible to pay value? so it is still somewhat possible to interact with chain and not completely out of reach to anyone? especially when "free" extrinsic that still take weight can drive the price up

_Originally posted by @mrq1911 in https://github.com/galacticcouncil/Basilisk-node/pull/610#discussion_r1200449960_

**Comment by Roznovjak** [comment]
The cost for `notePreimage` is `11 000 BSX fee + 33 000 BSX locked` for the upcoming wasm. So let's say you need `50k BSX` available.
@mrq1911 your current balance is `200k available` + `300k locked`. If you want to be able to note a preimage, max multiplier would be `4` (reached after 102 hours of full blocks).
The balance of council members vary from `66k to 10 MBSX`.
The max multiplier can be set to `200` (reached after 16 days of full blocks), if council members are willing to note a preimage.
